[tool.poetry]
name = "pysystemtrade"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.8"
pandas = "1.0.5"
matplotlib = ">=3.0.0"
PyYAML = "5.4"
numpy = ">=1.19.4"
scipy = ">=1.0.0"
pymongo = "3.9.0"
arctic = "1.79.2"
ib-insync = "0.9.70"
psutil = "5.6.6"
pytest = ">6.2"
Flask = ">=2.0.1"
Werkzeug = ">=2.0.1"
statsmodels = "0.12.2"
PyPDF2 = ">=2.5.0"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
