name: Slow test

on:
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ 3.9, 3.8, 3.7 ]

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pytest
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest --runslow  --disable-warnings

    #- name: Coverage report
    #  run: |
    #    coverage html
